version: '3'

services:
  go-scaffold:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - APP_ENV=production
      - TEMPLATE_DIR=/app/templates
    volumes:
      - ./templates:/app/templates
    restart: always
